name = "UKSF Taskforce Alpha - Core Modpack";
author = "UKSF Taskforce Alpha Team";
logo = "\z\z\z\uksfta\addons\mods\addons\mods\addons\main\data\icon_128_ca.paa";
logoOver = "\z\z\z\uksfta\addons\mods\addons\mods\addons\main\data\icon_128_highlight_ca.paa";
logoSmall = "\z\z\z\uksfta\addons\mods\addons\mods\addons\main\data\icon_64_ca.paa";
overview = "UKSF Taskforce Alpha - Core Modpack. Essential functional modifications and gameplay improvements.";
picture = "\z\z\z\uksfta\addons\mods\addons\mods\addons\main\data\title_co.paa";
tooltip = "UKSFTA Core";
tooltipOwned = "UKSF Taskforce Alpha";
