build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Update submodules to correct branch
      run: git submodule update --remote --checkout

    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
      with:
        annotate: false

    - name: Run HEMTT build
      run: hemtt build

    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@uksfta

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: uksfta-${{ github.sha }}-nobin
        path: .hemttout/@*
        include-hidden-files: true
