name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'UKSFTA/UKSFTA-Mods'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}